// backend/server.js
const express = require('express');
const cors = require('cors');

const app = express();
const PORT = 3001; // Choose a port for the backend

app.use(cors()); // Enable CORS for all routes
app.use(express.json()); // To parse JSON request bodies

// Dummy document generation function
const generateDummyDocuments = (query) => {
  return Array.from({ length: 5 }, (_, i) => {
    return `
## Document ${i + 1} for query: "${query}"

This is a **dummy document** generated by the server.

*   List item 1
*   List item 2

\`\`\`javascript
// Some code example
function hello() {
  console.log("Hello from document ${i + 1}!");
}
\`\`\`

You asked about: *${query.substring(0, 50)}...*

---
`;
  });
};

app.post('/api/retrieve-documents', (req, res) => {
  const { problem } = req.body;

  if (!problem || typeof problem !== 'string') {
    return res.status(400).json({ error: 'Invalid problem query provided.' });
  }

  console.log(`Received problem: "${problem}"`);

  // Simulate some delay
  setTimeout(() => {
    const documents = generateDummyDocuments(problem);
    res.json({ documents });
  }, 1000); // 1 second delay
});

app.listen(PORT, () => {
  console.log(`Backend server running on http://localhost:${PORT}`);
});